INSERT INTO pss_dvnx.tipo (id_tipo, nombre, "descripcion")
VALUES
  (1,  'Incidencia',       NULL),
  (2,  'Instalación',      NULL),
  (3,  'Aviso',            NULL),
  (4,  'Petición',         NULL),
  (5,  'Facturable',       NULL),
  (6,  'Duda',             NULL),
  (7,  'Desarrollo',       NULL),
  (8,  'Tarea',            NULL),
  (9,  'Ofertado',         NULL),
  (10, 'Llamada Overlay',  '');

INSERT INTO pss_dvnx.roles (name)
VALUES
  ('ADMIN'),
  ('EDITOR'),
  ('USER');

INSERT INTO  pss_dvnx.grupo (id_grupo, nombre, "descripcion")
VALUES
  (1, 'Administración',  NULL),
  (2, 'Comercial',       NULL),
  (3, 'Desarrollo',      NULL),
  (4, 'Gestión Central', NULL),
  (5, 'Logística',       NULL),
  (6, 'Movilidad',       NULL),
  (7, 'Post-Venta',      NULL),
  (8, 'Tiendas',         NULL);

INSERT INTO pss_dvnx.cliente (nombre)
VALUES
  ('AhorraCash/Bonacash'),
  ('Aitana'),
  ('Albir Garden'),
  ('Alifoods/Guillen'),
  ('Boprezo'),
  ('Campofresh'),
  ('Cardona'),
  ('Casalma'),
  ('Cash Zafra/MerkaCash'),
  ('Cifra'),
  ('Comercial Guadalupe'),
  ('Conepahi'),
  ('Continuos Levante'),
  ('Corbalan'),
  ('Donemes'),
  ('El Pino'),
  ('Excluib'),
  ('Exclusivas del Bebe'),
  ('Explotaciones Garajao'),
  ('Gestion Interna'),
  ('Hermanos Galiana'),
  ('HiperAsia'),
  ('Hiperber'),
  ('Hipergomera'),
  ('Infortien'),
  ('Kanali'),
  ('Kuups'),
  ('La Moixentina'),
  ('La Pedresina'),
  ('La Venta Nueva'),
  ('Leoter'),
  ('Lozano'),
  ('Marcial'),
  ('Martinez Hermanos'),
  ('Mendoza'),
  ('Morera Alimentacion'),
  ('Musgrave'),
  ('Pepe la Sal'),
  ('Personal'),
  ('Sabacomer'),
  ('Saura'),
  ('Serlodiex'),
  ('SM2000'),
  ('Spanish Style'),
  ('Super Avda La Palma'),
  ('Super G/Exclusivas Gutierrez'),
  ('Veragomera'),
  ('Yebenes'),
  ('Alcoop'),
  ('Antas'),
  ('MyMercat'),
  ('CostaBlanca'),
  ('Sabadar'),
  ('Abordo');
